"feature definition":
  - changed-files:
      - all-globs-to-any-file:
          - "features/*.yml"
          - "!features/*.yml.dist"

"documentation":
  - changed-files:
      - all-globs-to-any-file:
          - "**/*.md"

"tools and infrastructure":
  - changed-files:
      - all-globs-to-any-file:
          - "scripts/*.ts"
