draft_date: 2024-09-16
name: Managed Configuration API
description: TODO
spec: https://wicg.github.io/WebApiDevice/managed_config/
compat_features:
  - api.Navigator.managed
  - api.NavigatorManagedData
  - api.NavigatorManagedData.getManagedConfiguration
  - api.NavigatorManagedData.managedconfigurationchange_event
