title: Baseline
logo: /assets/img/baseline-wordmark.svg
description: >
  Baseline gives you clear information about which web platform features
  work across browsers.
show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal
