import child_process from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import url from 'url';

import { DefinedError } from "ajv";
import * as data from '../index.js';
import { validate } from "./validate.js";

let status: 0 | 1 = 0;

function checkGeneratedFileConsistency(): void {
    const quicktypePath: string = path.join(path.dirname(url.fileURLToPath(import.meta.url)), "../types.quicktype.ts");
    const quicktypeOnDisk: string = fs.readFileSync(quicktypePath, { encoding: "utf-8"});
    const quicktypeGenerated: string = child_process.execSync("npm run --silent schematypes", { encoding: "utf-8"});

    if (quicktypeOnDisk !== quicktypeGenerated) {
        console.error("There's a mismatch between the types generated by quicktype and the types in `types.quicktype.ts`.");
        console.error("This may produce misleading results for feature validation.");
        console.error("To fix this, run `npm run schematypes:write`.");
        status = 1;
    }
}

function valid() {
    const valid = validate(data);
    if (!valid) {
        // TODO: turn on strictNullChecks, fix all the errors, and replace this with:
        // const errors = validate.errors;
        const errors = (validate as any).errors as DefinedError[];
        for (const error of errors) {
            console.error(`${error.instancePath}: ${error.message}`);
        }
        status = 1;
    }
}

checkGeneratedFileConsistency();
valid();
process.exit(status);
