spec: https://drafts.csswg.org/selectors-4/#the-default-pseudo
caniuse: css-default-pseudo
status:
  baseline: high
  baseline_low_date: 2020-01-15
  support:
    chrome: "10"
    chrome_android: "18"
    edge: "79"
    firefox: "4"
    firefox_android: "4"
    safari: "5"
    safari_ios: "5"
