name: <base>
description: The `<base>` element sets the base URL (the URL that relative URLs are relative to) for all relative URLs in the document.
spec: https://html.spec.whatwg.org/multipage/semantics.html#the-base-element
group: html-elements
status:
  compute_from: html.elements.base
