name: <base>
description: The `<base>` element sets the base URL (the URL that relative URLs are relative to) for all relative URLs in the document.
spec: https://html.spec.whatwg.org/multipage/semantics.html#the-base-element
group: html-elements
status:
  compute_from: html.elements.base
compat_features:
  - api.HTMLBaseElement
  - api.HTMLBaseElement.href
  - api.HTMLBaseElement.target
  - html.elements.base
  - html.elements.base.href
  - html.elements.base.href.forbid_data_javascript_urls
  - html.elements.base.href.relative_url
  - html.elements.base.target
