name: ":default"
description: The `:default` CSS pseudo-class matches the default element in a group of related form controls, such as checkboxes and radio buttons with the `checked` attribute.
spec: https://drafts.csswg.org/selectors-4/#the-default-pseudo
group: selectors
caniuse: css-default-pseudo
