name: <meta>
description: The `<meta>` element represents metadata about the page used by the browser or search engines, including description, keywords, and character sets.
spec: https://html.spec.whatwg.org/multipage/semantics.html#meta
group: html-elements
status:
  compute_from: html.elements.meta
