name: <meta>
description: The `<meta>` element represents metadata about the page used by the browser or search engines, including description, keywords, and character sets.
spec: https://html.spec.whatwg.org/multipage/semantics.html#meta
group: html-elements
status:
  compute_from: html.elements.meta
compat_features:
  - api.HTMLMetaElement
  - api.HTMLMetaElement.content
  - api.HTMLMetaElement.httpEquiv
  - api.HTMLMetaElement.media
  - api.HTMLMetaElement.name
  - html.elements.meta
  - html.elements.meta.charset
  - html.elements.meta.content
  - html.elements.meta.http-equiv
  - html.elements.meta.http-equiv.content-type
  - html.elements.meta.http-equiv.refresh
  - html.elements.meta.name
  - html.elements.meta.name.referrer
