name: Service workers static routing
description: "The service worker install event's `addRoutes` method declares resource paths that should either be fetched from the network or the cache, to bypass the service worker and improve performance."
spec: https://w3c.github.io/ServiceWorker/
group: workers
compat_features:
  - api.InstallEvent
  - api.InstallEvent.InstallEvent
  - api.InstallEvent.addRoutes
