name: Update BCD tags

on:
  workflow_dispatch:

  schedule:
    - cron: "30 4 * * 1-5"

jobs:
  update-bcd-tags:
    if: github.repository == 'web-platform-dx/web-features'
    name: Update BCD tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm i
      - name: Checkout browser-compat-data
        uses: actions/checkout@v4'
        with:
          repository: mdn/browser-compat-data
          path: browser-compat-data
      - name: Run migration script
        run: npm run migrate-to-bcd ./browser-compat-data
      - name: Create BCD PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }} # need the rights to create and edit PRs
          commit-message: Update browser releases
          path: ./browser-compat-data
          signoff: false
          branch: migrate-web-features
          delete-branch: true
          title: "Migrate web-features tags"
          body: |
            This PR was automatically generated by an action in [web-platform-dx/web-features](https://github.com/web-platform-dx/web-features/blob/main/.github/workflows/update_bcd_tags.yml). This PR migrates the web-features feature mapping to BCD tags.
          draft: false
